services:

  db:
    image: postgres:15.3-alpine
    container_name: db
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: