services:

  db_test:
    image: postgres:15.3-alpine
    container_name: db_test
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_test_data: