[project]
name = "backend-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "fastapi-mail>=1.6.5",
    "fastapi[standard]>=0.136.3",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.14.1",
    "pyjwt>=2.13.0",
    "sqladmin[auth]>=0.31.1",
    "sqlalchemy>=2.0.50",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.15.15",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "B",
    "E", 
    "F",
    "I",
    "N",
    "Q",
    "PL",
    "RUF",
    "S",
    "T",
    "UP",
    "W",
]

# Ignore assertion errors in test files
[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]
