"""Cascade delete added email token and reset pass token

Revision ID: 08899a985f4c
Revises: 069e37137340
Create Date: 2026-09-13 20:12:32.843674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08899a985f4c'
down_revision: Union[str, Sequence[str], None] = '069e37137340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'email_verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('forgot_password_tokens_user_id_fkey'), 'forgot_password_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'forgot_password_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forgot_password_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('forgot_password_tokens_user_id_fkey'), 'forgot_password_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
