"""renamed avatar image field

Revision ID: bdc1675f3530
Revises: 25c270a5f7e3
Create Date: 2026-09-30 16:24:53.736264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc1675f3530'
down_revision: Union[str, Sequence[str], None] = '25c270a5f7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_key', sa.String(length=2048), nullable=True))
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_key')
    # ### end Alembic commands ###
